### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by Geo1088** [r-anime/awards-web#72]
Support more stuff like Safari on desktop and Edge. See `@babel/preset-env`

**Comment by JoseiToAoiTori** [comment]
Added the "wontfix" label because I've tried all sorts of polyfills and edge keeps breaking regardless with something new popping up everytime you add a polyfill. There's better things we can work on and maybe it's not out of the question that it'll actually become a usable browser in the future.

**Comment by JoseiToAoiTori** [comment]
Edge updated a while ago and now supports modern JavaScript features so the website works there now.
